data:
  - 'changelog*'
  - 'copyright*'
  - credits.txt
  - icon.png
  - keys.txt
  - license.txt
  - 'data/**/*'
  - 'images/**/*'
  - 'sounds/**/*'

game_code: &build
  - 'source/**'

macos:
  - 'XCode/**'
  - '**/*.xcodeproj'
  - 'icons/endless-sky.iconset/**'
  - 'utils/fetch_sdl2_framework.sh'
  - 'utils/set_dylibs_rpath.sh'
  - *build

windows:
  - '**/*.cbp'
  - EndlessSky.workspace
  - SConstruct
  - .winmake
  - *build

linux:
  - SConstruct
  - *build

unit_tests:
  - 'tests/unit/**/*.h'
  - 'tests/unit/**/*.hpp'
  - 'tests/unit/**/*.cpp'

integration_tests:
  - 'utils/test_parse.*'
  - 'tests/integration/run_tests*'
  - 'data/tests/**'
  - 'tests/integration/config/plugins/integration-tests/**'

codespell:
  - .codespell.exclude

xcode_files:
  - 'EndlessSky.xcodeproj/**'
  - 'utils/check_xcode.sh'

codeblocks_files:
  - '*.cbp'
  - 'utils/check_codeblocks.sh'

cmake_files:
  - CMakeLists.txt
  - source/CMakeLists.txt
  - tests/unit/CMakeLists.txt
  - tests/integration/IntegrationTests.cmake
  - CMakePresets.json
  - 'vcpkg/**'
  - vcpkg.json

copyright:
  - 'copyright'
