version: '{branch}.{build}'

skip_tags: true
skip_branch_with_pr: true

clone_depth: 2

environment:
  # Building with MinGW-w64 version 6.3.0. These env settings are used by the makefile.
  MINGW_ROOT: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
  ES_SRCLIB_DIR: ../lib/pkgd
  TEST_REPORT_FILE: .\tests\test-report.xml
  matrix:
    # - es_run_mode: 'dist'
    - es_run_mode: 'release'

install:
  - ps: |
      # Update env variables to use the desired MinGW version
      Set-AppveyorBuildVariable -Name PATH -Value "$Env:MINGW_ROOT\bin\;$Env:PATH";
      Set-AppveyorBuildVariable -Name DIR_MINGW64 -Value "$Env:MINGW_ROOT\x86_64-w64-mingw32";

      # Ensure we have the precompiled libraries to link with (SDL, etc.).
      if (!(Test-Path 'C:\dev64')) { New-Item 'C:\dev64' -ItemType Directory; }
      if (!(Test-Path 'C:\dev64\bin'))
      {
        Start-FileDownload 'http://endless-sky.github.io/win64-dev.zip' 'C:\dev64.zip'
        $zipArgs = 'x C:\dev64.zip -oC:\';
        Start-Process '7z.exe' -ArgumentList $zipArgs -Wait;
      }

cache:
  - C:\dev64
  - scons-local

build_script:
  - ps: mingw32-make.exe -r -e -f .winmake $Env:es_run_mode;
  - ps: mingw32-make.exe -r -e -f .winmake test;

before_test:
  - ps: |
      $here = (Get-Location).Path;
      Copy-Item -Path "bin\*\EndlessSky.exe" -Destination $here;
      Copy-Item -Path "C:\dev64\bin\*.dll" -Exclude "libstdc*" -Destination $here;

test_script:
  - ps: .\tests\bin\endless-sky-tests.exe -n es-ci -i --warn NoAssertions --order rand --rng-seed 'time' --filenames-as-tags -r junit -o $Env:TEST_REPORT_FILE;
  - ps: .\tests\test_parse.ps1 'EndlessSky.exe';

# Upload the build if tests passed.
after_test:
  - ps: |
      $here = (Get-Location).Path;
      Copy-Item -Path "$Env:DIR_MINGW64\lib\libstdc++-6.dll" -Destination $here;
      Copy-Item -Path "$Env:DIR_MINGW64\lib\libgcc_s_seh-1.dll" -Destination $here;
      Copy-Item -Path "$Env:DIR_MINGW64\lib\libwinpthread-1.dll" -Destination $here;

      # Zip the directory for release
      $ARCHIVE_NAME = "$Env:APPVEYOR_REPO_NAME-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_REPO_COMMIT-win64.7z";
      $ZIP_ARGS = "a $ARCHIVE_NAME .\*.exe -i!.\*.dll -i!.\data\ -i!.\icons\ -i!.\images\ -i!.\sounds\ -i!.\source\ -i!license.txt -i!copyright -i!README.md -i!changelog -i!credits.txt -i!keys.txt";
      Start-Process '7z.exe' -ArgumentList $ZIP_ARGS -Wait;
      Push-AppveyorArtifact $ARCHIVE_NAME;

# Upload the test report even if tests failed.
on_finish:
  - ps: ls . scons*
  - ps: |
      if (Test-Path $Env:TEST_REPORT_FILE)
      {
        (New-Object 'System.Net.WebClient').UploadFile(
          "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
          (Resolve-Path $Env:TEST_REPORT_FILE)
        );
      }
