name: Bug Report
description: Create a report to help us fix the game
labels: [bug, unconfirmed]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
        We know that filling this form out in full takes time, but we are also busy, unpaid volunteers--the more details you can provide, the smoother things will go.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can others reproduce the issue?
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: |
        If applicable, attach screenshots that may help others identify and resolve the issue.
        (If you are reporting a visual bug, a screenshot is effectively required!)
  - type: textarea
    attributes:
      label: Link to save file
      description: You can either upload your save here, or to e.g. hastebin / GitHub Gists
      placeholder: |
        Windows: %APPDATA%\endless-sky\saves
        Linux: ~/.local/share/endless-sky/saves
        macOS: ~/Library/Application Support/endless-sky/saves
  - type: input
    attributes:
      label: Operating System
      description: What OS do you use?
      placeholder: Windows 10 Pro, version 1803 build 17134.407
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Game Source
      description: From where did you obtain your current game version?
      options:
        - Steam
        - GOG
        - ESLauncher2
        - Built from source
        - GitHub Releases
        - Homebrew
        - Other (please describe)
    validations:
      required: true
  - type: input
    attributes:
      label: Game Version
      description: What game version are you running?
      placeholder: E.g. "v0.9.14" or "commit SHA cab74fd3"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context about the problem here that didn't fit into the form inputs above.
