name: Feature Request
description: Suggest an idea for this project

body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a feature request! This is a port of the endless-sky project, so for gameplay, art, or story updates, please check the [upstream issue reporter.](https://github.com/endless-sky/endless-sky/issues?q=is%3Aissue)
        For bugs involving the touchscreen ui or android usability, please post here. 
  - type: textarea
    attributes:
      label: Problem Description
      description: Provide a clear and concise description of what underlying issue is addressed by your feature request.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Related Issue Links
      description: |
        Provide links to other topics that have sought to address the same issue, or discussed this same idea. Include links to Steam, GitHub, Reddit, or Discord.
        (You can also address these related issues, to help differentiate your idea from those that have been dismissed in the past.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Solution
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Approaches
      description: Provide a clear and concise description of any alternative solutions or features you've considered that would also address the underlying issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here. If you're proposing new UI features, creating a mock-up can really go a long way in conveying your intent.
