name: Feature/Balance/Change Request
description: Suggest an idea or change for this project

body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a feature/change request! This project has been around for quite a while, so it is quite common for ideas to have come up before. To help save everyone's time, you are required to search for related issues and address any comments and concerns that arose previously.
        Otherwise, your issue will be closed--it is not fair to ask maintainers and collaborators to do background research for *your* feature request.

        Where should you search?
        - [GitHub Issues](https://github.com/endless-sky/endless-sky/issues?q=is%3Aissue)
        - [Steam Forum](https://steamcommunity.com/app/404410/discussions/)
        - [Discord Community](https://discord.gg/ZeuASSx)
        - [Reddit](https://reddit.com/r/endlesssky/)
  - type: textarea
    attributes:
      label: Problem Description
      description: Provide a clear and concise description of what underlying issue is addressed by your request.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Related Issue Links
      description: |
        Provide links to other topics that have sought to address the same issue, or discussed this same idea. Include links to Steam, GitHub, Reddit, or Discord.
        (You can also address these related issues, to help differentiate your idea from those that have been dismissed in the past.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Solution
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Approaches
      description: Provide a clear and concise description of any alternative solutions or features you've considered that would also address the underlying issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the request here. If you're proposing new UI features, creating a mock-up can really go a long way in conveying your intent.
