name: Documentation Issue
description: There is an error in documentation, such as documentation being wrong or outdated. Documentation may include the wiki on GitHub, RFCs, style guides, or other such pages/documents.
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: Thank you for filing a wiki report!
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide a clear and concise description of what the issue is.
    validations:
      required: true
