name: Check coding style

on:
  push:
    paths:
    - 'source/**'
    - 'tests/**'
  pull_request:
    paths:
    - 'source/**'
    - 'tests/**'

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install regex
    - name: Execute style checker
      run: python ./utils/check_code_style.py
