name: Manage labels

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  label-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Label merge conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
