name: Check coding style

on:
  push:
    paths:
    - 'source/**'
    - 'tests/**'
  pull_request:
    paths:
    - 'source/**'
    - 'tests/**'

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute style checker
      run: |
        OUT=$(./tests/check_coding_style.sh)
        if [ "${OUT}" != ""]; then
          echo "${OUT}"
          false
        fi
      shell: bash
